x-base:
  &base
  env_file:
    - ./.env
  networks:
    - teacher-tool-api
  restart: always

services:
  db:
    <<: *base
    image: postgres:16
    expose:
      - ${DATABASE_PORT}
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  migrate:
    <<: *base
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "./migrations", "-database", "postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME?sslmode=disable", "up" ]
    depends_on:
      - db

  app:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    container_name: teacher-tool-app
    depends_on:
      - db
      - migrate


networks:
  teacher-tool-api:

volumes:
  postgres-data:
