postgres:
  host: localhost
  port: 5432
  username: user
  password: pass
  db: shop
  MaxOpenConns: 25
  MaxIdleConns: 25
  ConnMaxIdleTime: 15m

app:
  host: 0.0.0.0
  port: 8080
  addr: :8080
  debug: false
  baseAPI: /api/v1
