postgres:
  host: db
  port: 5432
  username: user
  password: pass
  db: teacher
  MaxOpenConns: 25
  MaxIdleConns: 25
  ConnMaxIdleTime: 15m

app:
  host: 0.0.0.0
  port: 8000
  addr: :8000
  debug: false
  baseAPI: /api/v1
  secret: secret123!@#
  AccessHourTTL: 15
  RefreshHourTTL: 24
  CorsOrigins: [ "*" ]
  CorsMaxAge: 300

s3:
  AccessKey:
  SecretKey:
  BucketName:
  Endpoint:
  Region:
  StorageDomain: