basePath: /api/v1
definitions:
  github_com_iarsham_teacher-tool-api_internal_entities.PassChangeRequest:
    properties:
      confirm_password:
        example: 1qaz2wsx
        maxLength: 32
        minLength: 8
        type: string
      password:
        example: 1qaz2wsx
        maxLength: 32
        minLength: 8
        type: string
    required:
    - confirm_password
    - password
    type: object
  github_com_iarsham_teacher-tool-api_internal_entities.QuestionRequest:
    properties:
      file:
        $ref: '#/definitions/multipart.FileHeader'
      grade:
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        example: 5
        type: integer
      lesson:
        example: 1
        type: integer
      level:
        enum:
        - 0
        - 1
        - 2
        example: 2
        type: integer
      title:
        example: Math Stuff
        type: string
    required:
    - grade
    - lesson
    - level
    - title
    type: object
  github_com_iarsham_teacher-tool-api_internal_entities.RefreshTokenRequest:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
    required:
    - refresh_token
    type: object
  github_com_iarsham_teacher-tool-api_internal_entities.TemplateRequest:
    properties:
      file:
        $ref: '#/definitions/multipart.FileHeader'
    type: object
  github_com_iarsham_teacher-tool-api_internal_entities.UpdateUserRequest:
    properties:
      phone:
        example: "+9891154326250"
        maxLength: 15
        minLength: 10
        type: string
      role:
        enum:
        - 0
        - 1
        example: 1
        type: integer
    required:
    - phone
    type: object
  github_com_iarsham_teacher-tool-api_internal_entities.UserRequest:
    properties:
      password:
        example: 1qaz2wsx
        maxLength: 32
        minLength: 8
        type: string
      phone:
        example: "+9891154326250"
        maxLength: 15
        minLength: 10
        type: string
    required:
    - password
    - phone
    type: object
  github_com_iarsham_teacher-tool-api_internal_models.Templates:
    properties:
      created_at:
        example: "2024-01-29T03:09:00+03:30"
        type: string
      file:
        example: domain.com/media/file.docx
        type: string
      id:
        example: 1
        type: integer
      user_id:
        example: 1
        type: integer
    type: object
  multipart.FileHeader:
    properties:
      filename:
        type: string
      header:
        $ref: '#/definitions/textproto.MIMEHeader'
      size:
        type: integer
    type: object
  response.BadRequest:
    properties:
      error:
        example: bad request
        type: string
    type: object
  response.InternalServerError:
    properties:
      error:
        example: internal server error
        type: string
    type: object
  response.LoginSuccess:
    properties:
      accessToken:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
      refreshToken:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
    type: object
  response.PasswordChanged:
    properties:
      response:
        example: password changed successfully
        type: string
    type: object
  response.QuestionAlreadyExists:
    properties:
      error:
        example: question already exists
        type: string
    type: object
  response.QuestionCreated:
    properties:
      response:
        example: question created
        type: string
    type: object
  response.QuestionData:
    properties:
      createdAt:
        example: "2024-01-29T03:09:00+03:30"
        type: string
      file:
        example: domain.com/media/image.png
        type: string
      grade:
        example: fifth
        type: string
      id:
        example: 1
        type: integer
      lesson:
        example: "12"
        type: string
      level:
        example: advanced
        type: string
      title:
        example: Math statistics
        type: string
      used:
        example: 195
        type: integer
      userID:
        example: 10
        type: integer
      views:
        example: 666
        type: integer
    type: object
  response.QuestionNotFound:
    properties:
      error:
        example: question not found
        type: string
    type: object
  response.RefreshSuccess:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
    type: object
  response.TemplateCreated:
    properties:
      response:
        example: template created
        type: string
    type: object
  response.TemplateExists:
    properties:
      error:
        example: template already exists
        type: string
    type: object
  response.UserAlreadyExists:
    properties:
      error:
        example: user already exists
        type: string
    type: object
  response.UserCreated:
    properties:
      response:
        example: user created
        type: string
    type: object
  response.UserData:
    properties:
      created_at:
        example: "2024-01-29T03:09:00+03:30"
        type: string
      id:
        example: 1
        type: integer
      phone:
        example: "+989029266610"
        type: string
      role:
        example: 1
        type: integer
    type: object
  response.UserNotFound:
    properties:
      error:
        example: user not found
        type: string
    type: object
  response.WrongPassword:
    properties:
      error:
        example: wrong password
        type: string
    type: object
  response.questionResponse:
    properties:
      createdAt:
        example: "2024-01-29T03:09:00+03:30"
        type: string
      file:
        example: domain.com/media/image.png
        type: string
      grade:
        example: fifth
        type: string
      id:
        example: 1
        type: integer
      lesson:
        example: "12"
        type: string
      level:
        example: advanced
        type: string
      title:
        example: Math statistics
        type: string
      used:
        example: 195
        type: integer
      userID:
        example: 10
        type: integer
      views:
        example: 666
        type: integer
    type: object
  textproto.MIMEHeader:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
info:
  contact:
    email: arshamdev2001@gmail.com
    name: Arsham Roshannejad
    url: arsham.cloudarshamdev2001@gmail.com
  description: API for Teacher Tools application that provides various endpoints for
    managing data.
  license:
    name: MIT
    url: https://www.mit.edu/~amini/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: Teacher-Tools-API
  version: 0.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User data
        in: body
        name: userRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.UserNotFound'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.WrongPassword'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Login
      tags:
      - Auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh token endpoint to get new access token with refresh token
      parameters:
      - description: Token data
        in: body
        name: tokenRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RefreshSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Refresh token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User data
        in: body
        name: userRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.UserCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.UserAlreadyExists'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Register
      tags:
      - Auth
  /question:
    get:
      consumes:
      - application/json
      description: Get all questions handled by teacher
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.questionResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Get All Questions
      tags:
      - Questions
    post:
      consumes:
      - multipart/form-data
      description: Create a new question
      parameters:
      - description: Question data
        in: body
        name: questionRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.QuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.QuestionCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/response.QuestionAlreadyExists'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Create Question
      tags:
      - Questions
  /question/:id:
    delete:
      consumes:
      - application/json
      description: Delete question with id
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Delete Question
      tags:
      - Questions
    get:
      consumes:
      - application/json
      description: Get single question with id
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.QuestionData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.QuestionNotFound'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Get Question
      tags:
      - Questions
  /template:
    get:
      description: Get all templates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_models.Templates'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Get Templates
      tags:
      - Templates
    post:
      consumes:
      - multipart/form-data
      description: Create a new template for exam
      parameters:
      - description: Template data
        in: body
        name: templateRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.TemplateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.TemplateCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/response.TemplateExists'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Create Template
      tags:
      - Templates
  /template/{id}:
    delete:
      description: Delete a template with id
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Delete Template
      tags:
      - Templates
  /user:
    delete:
      consumes:
      - application/json
      description: Delete a user based on jwt and current user
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Delete User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Get a user data and properties
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.UserNotFound'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Get User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user based on jwt and current user
      parameters:
      - description: User data
        in: body
        name: userRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Update User
      tags:
      - Users
  /user/change-password:
    post:
      consumes:
      - application/json
      description: Change user password
      parameters:
      - description: User data
        in: body
        name: userRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.PassChangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PasswordChanged'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Password Change
      tags:
      - Users
swagger: "2.0"
