basePath: /api/v1
definitions:
  github_com_iarsham_teacher-tool-api_internal_entities.UpdateUserRequest:
    properties:
      phone:
        example: "+9891154326250"
        maxLength: 15
        minLength: 10
        type: string
      role:
        enum:
        - 0
        - 1
        example: 1
        type: integer
    required:
    - phone
    type: object
  github_com_iarsham_teacher-tool-api_internal_entities.UserRequest:
    properties:
      password:
        example: 1qaz2wsx
        maxLength: 32
        minLength: 8
        type: string
      phone:
        example: "+9891154326250"
        maxLength: 15
        minLength: 10
        type: string
    required:
    - password
    - phone
    type: object
  response.BadRequest:
    properties:
      error:
        example: bad request
        type: string
    type: object
  response.HealthCheck:
    properties:
      status:
        example: available
        type: string
    type: object
  response.InternalServerError:
    properties:
      error:
        example: internal server error
        type: string
    type: object
  response.LoginSuccess:
    properties:
      accessToken:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
      refreshToken:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
    type: object
  response.UserAlreadyExists:
    properties:
      error:
        example: user already exists
        type: string
    type: object
  response.UserCreated:
    properties:
      response:
        example: user created
        type: string
    type: object
  response.UserData:
    properties:
      created_at:
        example: "2024-01-29T03:09:00+03:30"
        type: string
      id:
        example: 1
        type: integer
      phone:
        example: "+989029266610"
        type: string
      role:
        example: 1
        type: integer
    type: object
  response.UserNotFound:
    properties:
      error:
        example: user not found
        type: string
    type: object
  response.WrongPassword:
    properties:
      error:
        example: wrong password
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: arshamdev2001@gmail.com
    name: Arsham Roshannejad
    url: arsham.cloudarshamdev2001@gmail.com
  description: API for Teacher Tools application that provides various endpoints for
    managing data.
  license:
    name: MIT
    url: https://www.mit.edu/~amini/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: Teacher-Tools-API
  version: 0.0.0
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.HealthCheck'
      summary: Health check
      tags:
      - Server
  /login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User data
        in: body
        name: userRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.UserNotFound'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.WrongPassword'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Login
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User data
        in: body
        name: userRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.UserCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.UserAlreadyExists'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Register
      tags:
      - Auth
  /user:
    delete:
      consumes:
      - application/json
      description: Delete a user based on jwt and current user
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Delete User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Get a user data and properties
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.UserNotFound'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Get User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user based on jwt and current user
      parameters:
      - description: User data
        in: body
        name: userRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_iarsham_teacher-tool-api_internal_entities.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequest'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.InternalServerError'
      summary: Update User
      tags:
      - Users
swagger: "2.0"
